vite_app_deploy_developer_user: "{{ developer_user | default('developer') }}"
vite_app_deploy_developer_home: "{{ developer_home | default('/home/developer') }}"
vite_app_deploy_node_default_version: "{{ node_default_version | default('24.14.0') }}"

vite_app_deploy_github_username: "{{ github_username | default('') }}"
vite_app_deploy_github_token: "{{ github_token | default('') }}"
vite_app_deploy_github_persist_auth_in_remote: "{{ github_persist_auth_in_remote | default(true) }}"
